# Generated by Django 5.2.17 on 2026-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_normalize_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_scan_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
