# Generated by Django 5.2.17 on 2026-10-07 09:10

import concerts.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_ticket_admin_scan_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=concerts.uploads.proof_upload_path),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
