# Generated by Django 5.2.17 on 2026-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_optional_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
