# Generated by Django 5.2.17 on 2026-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_optional_order_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='details',
            field=models.TextField(blank=True, help_text='Подробности, которые откроются в окне по кнопке ! на карточке.'),
        ),
    ]
