server {
    listen 8068;
    listen [::]:8068;
    server_name 77.83.206.140;

    return 301 https://majormotors.uz$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name majormotors.uz www.majormotors.uz;

    client_max_body_size 12m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location /static/ {
        alias /var/www/koncrept/staticfiles/;
        access_log off;
        expires 7d;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    location / {
        proxy_pass http://unix:/run/koncrept/gunicorn.sock;
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
